=== brad-x/portage-layman/metadata/dtd/metadata.dtd
<!-- Metadata for a category -->
<!ELEMENT catmetadata ( (longdescription)* )>
<!ATTLIST catmetadata pkgname CDATA "">

<!-- Metadata for a package -->
<!ELEMENT pkgmetadata ( (maintainer|natural-name|longdescription|slots|use|upstream)* )>
<!ATTLIST pkgmetadata pkgname CDATA "">

  <!-- One tag for each maintainer of a package, multiple allowed-->
  <!ELEMENT maintainer ( email, (description| name)* )>
  <!-- type attribute determines whether the maintainer is a person or a project.
    Unknown is added to handle <maintainer/>s in <upstream/>s. Using it (or no
    explicit type) for Gentoo maintainers is prohibited. -->
  <!ATTLIST maintainer type (person|project|unknown) "unknown">

  <!-- Natural name for package, example: LibreOffice (for app-office/libreoffice) -->
  <!ELEMENT natural-name (#PCDATA) >

  <!-- A long description of the package in freetext-->
  <!ELEMENT longdescription (#PCDATA|pkg|cat)* >

  <!-- A description of the packages SLOTs -->
  <!ELEMENT slots ((slot)*,subslots?) >
    <!-- A particular SLOT -->
    <!ELEMENT slot (#PCDATA)* >
      <!-- name attribute holds the name of the SLOT, for sub-SLOTS use the subslots element -->
      <!ATTLIST slot name CDATA #REQUIRED >
    <!-- The meaning of sub-SLOTs for the whole package -->
    <!ELEMENT subslots (#PCDATA)* >

  <!-- description of what this USE flag does for this package -->
  <!ELEMENT use (flag)* >
    <!ELEMENT flag (#PCDATA|pkg|cat)* >
      <!-- name attribute holds the name of the USE flag -->
      <!ATTLIST flag name CDATA #REQUIRED >

  <!-- upstream metadata information (maintainers, upstream docs,..) -->
  <!ELEMENT upstream (maintainer|changelog|doc|bugs-to|remote-id)* >
    <!-- Due to the limitation of DTD this will also allow a status
      attribute for the package maintainer element. Please note that
      the usage of the status attribute is nevertheless _only_ allowed
      in the upstream maintainer element. -->
    <!ATTLIST maintainer status (active|inactive|unknown) "unknown" >
    <!-- URL where the upstream changelog can be found -->
    <!ELEMENT changelog (#PCDATA)>
    <!-- URL where the location of the upstream documentation can be found -->
    <!ELEMENT doc (#PCDATA)>
      <!ATTLIST doc lang CDATA "C" >
    <!-- location where to report bugs
      (may also be an email address prefixed with mailto:) -->
    <!ELEMENT bugs-to (#PCDATA)>
    <!-- specify a type of package identification tracker -->
    <!ELEMENT remote-id (#PCDATA)>
      <!ATTLIST remote-id type (bitbucket|cpan|cpan-module|cpe|cran|ctan|freecode|freshmeat|github|gitlab|gitorious|google-code|launchpad|pear|pecl|pypi|rubyforge|rubygems|sourceforge|sourceforge-jp|vim) #REQUIRED>

  <!-- category/package information for cross-linking in descriptions
    and useflag descriptions -->
  <!ELEMENT pkg (#PCDATA) >
  <!ELEMENT cat (#PCDATA) >
          
<!-- Common attributes -->

<!-- the lang attribute, specifies the language of this tag. This is 
  only useful for descriptions of various kinds. If a tag with this 
  attribute is included there must be a description in the default 
  language "C" or "en", which is equivalent -->
  <!ATTLIST description lang CDATA "C" >
  <!ATTLIST longdescription lang CDATA "C" >
  <!ATTLIST slots lang CDATA "C" >
  <!ATTLIST use lang CDATA "C" >

<!-- The restrict attribute, this attribute specifies restrictions on 
  the applicability of tags on versions. The format of this attribute is 
  equal to the format of DEPEND lines in ebuilds. There is one special 
  value though: restrict="*". A tag that specifies this only applies if 
  there are no other tags that apply.
  
  For required tags, there must be either an unrestricted version, or a 
  version that is default restricted. -->
  <!ATTLIST maintainer restrict CDATA #IMPLIED >
  <!ATTLIST longdescription restrict CDATA #IMPLIED >
  <!ATTLIST flag restrict CDATA #IMPLIED >

<!-- standard parts -->
<!-- an email address -->
<!ELEMENT email (#PCDATA) >
<!-- the name of a person (maintainer, contributor) -->
<!ELEMENT name (#PCDATA) >
<!-- A description of a maintainer or change -->
<!ELEMENT description (#PCDATA) >

=== brad-x/portage-layman/dev-python/guessit/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <herd>proxy-maintainers</herd>
  <maintainer>
    <email>nikoli@gmx.us</email>
    <name>Nikoli</name>
  </maintainer>
  <upstream>
    <remote-id type="pypi">guessit</remote-id>
    <remote-id type="github">wackou/guessit</remote-id>
  </upstream>
</pkgmetadata>

=== brad-x/portage-layman/net-libs/http-parser/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<herd>proxy-maintainers</herd>
	<maintainer>
		<email>bugs@bergstroem.nu</email>
		<name>Johan BergstrÃ¶m</name>
		<description>Proxied Maintainer</description>
	</maintainer>
	<upstream>
		<remote-id type="github">joyent/http-parser</remote-id>
	</upstream>
</pkgmetadata>

=== brad-x/portage-layman/www-apps/bugzilla/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<herd>proxy-maintainers</herd>
	<maintainer>
		<email>gentoo@xayto.net</email>
		<name>Craig Inches</name>
		<description>Proxied maintainer; set to assignee in all bugs</description>
	</maintainer>
	<herd>web-apps</herd>
	<use>
		<flag name="extras">Optional Perl modules</flag>
		<flag name="modperl">Enable <pkg>www-apache/mod_perl</pkg> support</flag>
	</use>
</pkgmetadata>

=== brad-x/portage-layman/games-engines/scummvm/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <herd>games</herd>
  <use>
    <flag name="fluidsynth">compile with support for fluidsynth</flag>
    <flag name="mpeg2">enable mpeg2 codec for cutscenes</flag>
    <flag name="unsupported">enable unsupported and/or broken game engines (you're on your own)</flag>
  </use>
  <upstream>
    <remote-id type="sourceforge">scummvm</remote-id>
  </upstream>
</pkgmetadata>

=== brad-x/portage-layman/dev-ruby/faraday_middleware/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<herd>ruby</herd>
	<maintainer>
		<email>robbat2@gentoo.org</email>
		<name>Robin H. Johnson</name>
	</maintainer>
	<longdescription lang="en">
		A collection of useful Faraday middleware.
	</longdescription>
	<use>
		<flag name="parsexml">Include FaradayMiddleware::ParseXml</flag>
		<flag name="oauth">Include FaradayMiddleware::OAuth</flag>
		<flag name="mashify">Include FaradayMiddleware::Mashify</flag>
		<flag name="rashify">Include FaradayMiddleware::Rashify</flag>
	</use>
	<upstream>
		<remote-id type="github">lostisland/faraday_middleware</remote-id>
	</upstream>
</pkgmetadata>

=== brad-x/portage-layman/mail-client/trojita/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<herd>qt</herd>
	<herd>kde</herd>
	<maintainer>
		<email>jkt@gentoo.org</email>
		<name>Jan Kundr√°t</name>
	</maintainer>
	<use>
		<flag name="password">Store passwords securely via <pkg>dev-libs/qtkeychain</pkg></flag>
	</use>
	<upstream>
		<remote-id type="sourceforge">trojita</remote-id>
	</upstream>
</pkgmetadata>

=== brad-x/portage-layman/dev-python/tmdb3/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <herd>python</herd>
  <maintainer>
    <email>floppym@gentoo.org</email>
    <name>Mike Gilbert</name>
  </maintainer>
  <upstream>
    <remote-id type="pypi">tmdb3</remote-id>
    <remote-id type="github">wagnerrp/pytmdb3</remote-id>
  </upstream>
</pkgmetadata>

=== brad-x/portage-layman/dev-lua/lua-openssl/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<herd>proxy-maintainers</herd>
	<maintainer>
		<email>jakub@jirutka.cz</email>
		<name>Jakub Jirutka</name>
	</maintainer>
	<use>
		<flag name="luajit">Use <pkg>dev-lang/luajit</pkg> instead of
			<pkg>dev-lang/lua</pkg></flag>
	</use>
	<upstream>
		<remote-id type="github">zhaozg/lua-openssl</remote-id>
	</upstream>
</pkgmetadata>
