=== brad-x/portage-layman/metadata/dtd/metadata.dtd
<!-- Metadata for a category -->
<!ELEMENT catmetadata ( (longdescription)* )>
<!ATTLIST catmetadata pkgname CDATA "">

<!-- Metadata for a package -->
<!ELEMENT pkgmetadata ( (maintainer|natural-name|longdescription|slots|use|upstream)* )>
<!ATTLIST pkgmetadata pkgname CDATA "">

  <!-- One tag for each maintainer of a package, multiple allowed-->
  <!ELEMENT maintainer ( email, (description| name)* )>
  <!-- type attribute determines whether the maintainer is a person or a project.
    Unknown is added to handle <maintainer/>s in <upstream/>s. Using it (or no
    explicit type) for Gentoo maintainers is prohibited. -->
  <!ATTLIST maintainer type (person|project|unknown) "unknown">

  <!-- Natural name for package, example: LibreOffice (for app-office/libreoffice) -->
  <!ELEMENT natural-name (#PCDATA) >

  <!-- A long description of the package in freetext-->
  <!ELEMENT longdescription (#PCDATA|pkg|cat)* >

  <!-- A description of the packages SLOTs -->
  <!ELEMENT slots ((slot)*,subslots?) >
    <!-- A particular SLOT -->
    <!ELEMENT slot (#PCDATA)* >
      <!-- name attribute holds the name of the SLOT, for sub-SLOTS use the subslots element -->
      <!ATTLIST slot name CDATA #REQUIRED >
    <!-- The meaning of sub-SLOTs for the whole package -->
    <!ELEMENT subslots (#PCDATA)* >

  <!-- description of what this USE flag does for this package -->
  <!ELEMENT use (flag)* >
    <!ELEMENT flag (#PCDATA|pkg|cat)* >
      <!-- name attribute holds the name of the USE flag -->
      <!ATTLIST flag name CDATA #REQUIRED >

  <!-- upstream metadata information (maintainers, upstream docs,..) -->
  <!ELEMENT upstream (maintainer|changelog|doc|bugs-to|remote-id)* >
    <!-- Due to the limitation of DTD this will also allow a status
      attribute for the package maintainer element. Please note that
      the usage of the status attribute is nevertheless _only_ allowed
      in the upstream maintainer element. -->
    <!ATTLIST maintainer status (active|inactive|unknown) "unknown" >
    <!-- URL where the upstream changelog can be found -->
    <!ELEMENT changelog (#PCDATA)>
    <!-- URL where the location of the upstream documentation can be found -->
    <!ELEMENT doc (#PCDATA)>
      <!ATTLIST doc lang CDATA "C" >
    <!-- location where to report bugs
      (may also be an email address prefixed with mailto:) -->
    <!ELEMENT bugs-to (#PCDATA)>
    <!-- specify a type of package identification tracker -->
    <!ELEMENT remote-id (#PCDATA)>
      <!ATTLIST remote-id type (bitbucket|cpan|cpan-module|cpe|cran|ctan|freecode|freshmeat|github|gitlab|gitorious|google-code|launchpad|pear|pecl|pypi|rubyforge|rubygems|sourceforge|sourceforge-jp|vim) #REQUIRED>

  <!-- category/package information for cross-linking in descriptions
    and useflag descriptions -->
  <!ELEMENT pkg (#PCDATA) >
  <!ELEMENT cat (#PCDATA) >
          
<!-- Common attributes -->

<!-- the lang attribute, specifies the language of this tag. This is 
  only useful for descriptions of various kinds. If a tag with this 
  attribute is included there must be a description in the default 
  language "C" or "en", which is equivalent -->
  <!ATTLIST description lang CDATA "C" >
  <!ATTLIST longdescription lang CDATA "C" >
  <!ATTLIST slots lang CDATA "C" >
  <!ATTLIST use lang CDATA "C" >

<!-- The restrict attribute, this attribute specifies restrictions on 
  the applicability of tags on versions. The format of this attribute is 
  equal to the format of DEPEND lines in ebuilds. There is one special 
  value though: restrict="*". A tag that specifies this only applies if 
  there are no other tags that apply.
  
  For required tags, there must be either an unrestricted version, or a 
  version that is default restricted. -->
  <!ATTLIST maintainer restrict CDATA #IMPLIED >
  <!ATTLIST longdescription restrict CDATA #IMPLIED >
  <!ATTLIST flag restrict CDATA #IMPLIED >

<!-- standard parts -->
<!-- an email address -->
<!ELEMENT email (#PCDATA) >
<!-- the name of a person (maintainer, contributor) -->
<!ELEMENT name (#PCDATA) >
<!-- A description of a maintainer or change -->
<!ELEMENT description (#PCDATA) >

=== brad-x/portage-layman/app-admin/ansible/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <maintainer>
    <email>pinkbyte@gentoo.org</email>
    <name>Sergey Popov</name>
  </maintainer>
  <maintainer>
    <email>chainsaw@gentoo.org</email>
    <name>Tony Vroon</name>
  </maintainer>
  <maintainer>
    <email>prometheanfire@gentoo.org</email>
    <name>Matthew Thode</name>
  </maintainer>
  <upstream>
    <remote-id type="pypi">ansible</remote-id>
    <remote-id type="github">ansible/ansible</remote-id>
    <bugs-to>https://github.com/ansible/ansible/issues</bugs-to>
  </upstream>
  <longdescription lang="en">
Radically simple deployment, model-driven configuration management, and 
command execution framework.
</longdescription>
</pkgmetadata>

=== brad-x/portage-layman/media-sound/teamspeak-server-bin/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<herd>proxy-maintainers</herd>
	<maintainer>
		<email>ck+gentoobugzilla@bl4ckb0x.de</email>
		<name>Conrad Kostecki</name>
		<description>Proxy maintaine, assign bugs to him</description>
	</maintainer>
	<longdescription>TeamSpeak Server (Voice Communication Software)</longdescription>
	<use>
		<flag name="tsdns">Make use of TeamSpeak DNS.</flag>
	</use>
</pkgmetadata>

=== brad-x/portage-layman/net-wireless/hackrf-tools/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<herd>radio</herd>
	<maintainer>
		<email>zerochaos@gentoo.org</email>
		<name>Rick Farina</name>
	</maintainer>
	<longdescription lang="en">
</longdescription>
	<upstream>
		<remote-id type="sourceforge">hackrf</remote-id>
		<remote-id type="github">mossmann/hackrf</remote-id>
	</upstream>
</pkgmetadata>

=== brad-x/portage-layman/app-laptop/nvidiabl/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<herd>proxy-maintainers</herd>
	<maintainer>
		<email>gentoobugzilla@jeltef.nl</email>
		<name>Jelte Fennema</name>
		<description>Proxied maintainer; set to assignee in all bugs</description>
	</maintainer>
	<upstream>
		<remote-id type="github">guillaumezin/nvidiabl</remote-id>
	</upstream>
</pkgmetadata>

=== brad-x/portage-layman/dev-python/zake/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <herd>openstack</herd>
  <maintainer>
    <email>prometheanfire@gentoo.org</email>
    <name>Matthew Thode</name>
  </maintainer>
  <longdescription lang="en">
  A python package that works to provide a nice set of testing utilities for the kazoo library.
  </longdescription>
  <upstream>
    <remote-id type="pypi">zake</remote-id>
    <remote-id type="github">yahoo/Zake</remote-id>
  </upstream>
</pkgmetadata>

=== brad-x/portage-layman/games-roguelike/dwarf-fortress/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
<herd>proxy-maintainers</herd>
<maintainer>
	<email>alex_y_xu@yahoo.ca</email>
	<name>Alex Xu</name>
	<description>proxied maintainer, please assign bugs to</description>
</maintainer>
<maintainer>
	<email>creffett@gentoo.org</email>
	<name>Chris Reffett</name>
	<description>maintainer, please CC on bugs</description>
</maintainer>
</pkgmetadata>

=== brad-x/portage-layman/media-libs/gst-plugins-base/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="project">
    <email>gstreamer@gentoo.org</email>
    <name>GStreamer package maintainers</name>
	</maintainer>
	<use>
		<flag name="ivorbis">Enable integer based vorbis decoder</flag>
		<flag name="opus">Enable opus codec support</flag>
		<flag name="pango">Enable pango GStreamer plugin</flag>
    </use>
</pkgmetadata>

=== brad-x/portage-layman/sys-apps/udevil/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<herd>proxy-maintainers</herd>
	<maintainer>
		<email>zlg@gentoo.org</email>
		<name>Daniel Campbell</name>
	</maintainer>
	<maintainer>
		<email>ThyArmageddon+Gentoo@Gmail.com</email>
		<name>Elijah El Lazkani</name>
	</maintainer>
	<upstream>
		<remote-id type="github">IgnorantGuru/udevil</remote-id>
	</upstream>
</pkgmetadata>
