=== brad-x/portage-layman/metadata/dtd/metadata.dtd
<!-- Metadata for a category -->
<!ELEMENT catmetadata ( (longdescription)* )>
<!ATTLIST catmetadata pkgname CDATA "">

<!-- Metadata for a package -->
<!ELEMENT pkgmetadata ( (maintainer|natural-name|longdescription|slots|use|upstream)* )>
<!ATTLIST pkgmetadata pkgname CDATA "">

  <!-- One tag for each maintainer of a package, multiple allowed-->
  <!ELEMENT maintainer ( email, (description| name)* )>
  <!-- type attribute determines whether the maintainer is a person or a project.
    Unknown is added to handle <maintainer/>s in <upstream/>s. Using it (or no
    explicit type) for Gentoo maintainers is prohibited. -->
  <!ATTLIST maintainer type (person|project|unknown) "unknown">

  <!-- Natural name for package, example: LibreOffice (for app-office/libreoffice) -->
  <!ELEMENT natural-name (#PCDATA) >

  <!-- A long description of the package in freetext-->
  <!ELEMENT longdescription (#PCDATA|pkg|cat)* >

  <!-- A description of the packages SLOTs -->
  <!ELEMENT slots ((slot)*,subslots?) >
    <!-- A particular SLOT -->
    <!ELEMENT slot (#PCDATA)* >
      <!-- name attribute holds the name of the SLOT, for sub-SLOTS use the subslots element -->
      <!ATTLIST slot name CDATA #REQUIRED >
    <!-- The meaning of sub-SLOTs for the whole package -->
    <!ELEMENT subslots (#PCDATA)* >

  <!-- description of what this USE flag does for this package -->
  <!ELEMENT use (flag)* >
    <!ELEMENT flag (#PCDATA|pkg|cat)* >
      <!-- name attribute holds the name of the USE flag -->
      <!ATTLIST flag name CDATA #REQUIRED >

  <!-- upstream metadata information (maintainers, upstream docs,..) -->
  <!ELEMENT upstream (maintainer|changelog|doc|bugs-to|remote-id)* >
    <!-- Due to the limitation of DTD this will also allow a status
      attribute for the package maintainer element. Please note that
      the usage of the status attribute is nevertheless _only_ allowed
      in the upstream maintainer element. -->
    <!ATTLIST maintainer status (active|inactive|unknown) "unknown" >
    <!-- URL where the upstream changelog can be found -->
    <!ELEMENT changelog (#PCDATA)>
    <!-- URL where the location of the upstream documentation can be found -->
    <!ELEMENT doc (#PCDATA)>
      <!ATTLIST doc lang CDATA "C" >
    <!-- location where to report bugs
      (may also be an email address prefixed with mailto:) -->
    <!ELEMENT bugs-to (#PCDATA)>
    <!-- specify a type of package identification tracker -->
    <!ELEMENT remote-id (#PCDATA)>
      <!ATTLIST remote-id type (bitbucket|cpan|cpan-module|cpe|cran|ctan|freecode|freshmeat|github|gitlab|gitorious|google-code|launchpad|pear|pecl|pypi|rubyforge|rubygems|sourceforge|sourceforge-jp|vim) #REQUIRED>

  <!-- category/package information for cross-linking in descriptions
    and useflag descriptions -->
  <!ELEMENT pkg (#PCDATA) >
  <!ELEMENT cat (#PCDATA) >
          
<!-- Common attributes -->

<!-- the lang attribute, specifies the language of this tag. This is 
  only useful for descriptions of various kinds. If a tag with this 
  attribute is included there must be a description in the default 
  language "C" or "en", which is equivalent -->
  <!ATTLIST description lang CDATA "C" >
  <!ATTLIST longdescription lang CDATA "C" >
  <!ATTLIST slots lang CDATA "C" >
  <!ATTLIST use lang CDATA "C" >

<!-- The restrict attribute, this attribute specifies restrictions on 
  the applicability of tags on versions. The format of this attribute is 
  equal to the format of DEPEND lines in ebuilds. There is one special 
  value though: restrict="*". A tag that specifies this only applies if 
  there are no other tags that apply.
  
  For required tags, there must be either an unrestricted version, or a 
  version that is default restricted. -->
  <!ATTLIST maintainer restrict CDATA #IMPLIED >
  <!ATTLIST longdescription restrict CDATA #IMPLIED >
  <!ATTLIST flag restrict CDATA #IMPLIED >

<!-- standard parts -->
<!-- an email address -->
<!ELEMENT email (#PCDATA) >
<!-- the name of a person (maintainer, contributor) -->
<!ELEMENT name (#PCDATA) >
<!-- A description of a maintainer or change -->
<!ELEMENT description (#PCDATA) >

=== brad-x/portage-layman/net-misc/pycnb/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <herd>python</herd>
  <maintainer>
    <email>yac@gentoo.org</email>
    <name>Jan Matejka</name>
  </maintainer>
  <longdescription lang="en">
	</longdescription>
  <upstream>
    <remote-id type="pypi">pycnb</remote-id>
    <remote-id type="github">yaccz/pycnb</remote-id>
  </upstream>
</pkgmetadata>

=== brad-x/portage-layman/app-admin/rex/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<herd>proxy-maintainers</herd>
	<maintainer>
		<email>erkiferenc@gmail.com</email>
		<name>Ferenc Erki</name>
	</maintainer>
	<maintainer>
		<email>patrick@gentoo.org</email>
		<name>Patrick Lauer</name>
	</maintainer>
</pkgmetadata>

=== brad-x/portage-layman/dev-python/alembic/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <herd>python</herd>
  <maintainer>
    <email>yac@gentoo.org</email>
    <name>Jan MatÄ›jka</name>
  </maintainer>
  <upstream>
    <remote-id type="pypi">alembic</remote-id>
    <remote-id type="bitbucket">zzzeek/alembic</remote-id>
  </upstream>
</pkgmetadata>

=== brad-x/portage-layman/sys-devel/byfl/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer>
		<email>ottxor@gentoo.org</email>
		<name>Christoph Junghans</name>
	</maintainer>
	<use>
		<flag name="dragonegg">Add support for non C languages through <pkg>sys-devel/dragonegg</pkg></flag>
	</use>
	<upstream>
		<remote-id type="github">losalamos/Byfl</remote-id>
	</upstream>
</pkgmetadata>

=== brad-x/portage-layman/dev-php/pecl-mysqlnd_qc/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <herd>php</herd>
  <herd>proxy-maintainers</herd>
  <maintainer>
    <email>olemarkus@gentoo.org</email>
  </maintainer>
  <maintainer>
	  <email>pavel@senbonzakura.eu</email>
    <description>Proxied co-maintainer, CC on all bugs</description>
  </maintainer>
  <use>
    <flag name="memcached">Use <pkg>dev-libs/libmemcached</pkg> as a storage handler</flag>
    <flag name="sqlite">Use <pkg>dev-db/sqlite</pkg> as a storage handler</flag>
  </use>
</pkgmetadata>

=== brad-x/portage-layman/dev-ruby/semantic_puppet/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<herd>ruby</herd>
	<maintainer>
		<email>robbat2@gentoo.org</email>
		<name>Robin H. Johnson</name>
	</maintainer>
	<longdescription lang="en">
		Library of useful tools for working with Semantic Versions and module dependencies.
	</longdescription>
	<upstream>
		<remote-id type="github">puppetlabs/semantic_puppet</remote-id>
	</upstream>
</pkgmetadata>

=== brad-x/portage-layman/dev-python/jenkins-webapi/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <herd>proxy-maintainers</herd>
  <maintainer>
    <email>idella4@gentoo.org</email>
  </maintainer>
  <maintainer>
    <email>hydrapolic@gmail.com</email>
    <name>Tomas Mozes</name>
    <description>Proxy maintainer and target for any bugs</description>
  </maintainer>
  <upstream>
    <remote-id type="github">gvalkov/jenkins-webapi</remote-id>
  </upstream>
</pkgmetadata>

=== brad-x/portage-layman/dev-python/python-digest/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <herd>python</herd>
  <maintainer>
    <email>idella4@gentoo.org</email>
    <name>Ian Delaney</name>
  </maintainer>
  <upstream>
    <remote-id type="pypi">python-digest</remote-id>
    <remote-id type="bitbucket">akoha/python-digest</remote-id>
  </upstream>
</pkgmetadata>
